title: Camila Areias PhD
description: A blog about my career trajectory and goals
theme: jekyll-theme-minimal
author: Camila

permalink: /:year/:month/:day/:title/

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

